name: stage CD

on:
  pull_request:
    types:
      - closed
      
jobs:
  update-tags:
    uses: GlueOps/github-workflows/.github/workflows/argocd-tags-ci.yml@main
    if: github.event.pull_request.merged == true
    secrets: inherit
    with:
      ENV: 'staging'
      CREATE_PR: false
      STACK_REPO: 'deployment-configurations'
